//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagementAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookManagementEntities : DbContext
    {
        public BookManagementEntities()
            : base("name=BookManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Cover> Covers { get; set; }
        //public virtual DbSet<Rolefunction> Rolefunctions { get; set; }
        //public virtual DbSet<User> Users { get; set; }
        //public virtual DbSet<Userrole> Userroles { get; set; }
    }
}
